# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Configurator_pb2 as Configurator__pb2


class ConfiguratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfiguration = channel.unary_stream(
                '/snapshot.Configurator/GetConfiguration',
                request_serializer=Configurator__pb2.ConfigurationRequest.SerializeToString,
                response_deserializer=Configurator__pb2.ConfigurationContainer.FromString,
                )


class ConfiguratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfiguratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfiguration': grpc.unary_stream_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=Configurator__pb2.ConfigurationRequest.FromString,
                    response_serializer=Configurator__pb2.ConfigurationContainer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snapshot.Configurator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Configurator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/snapshot.Configurator/GetConfiguration',
            Configurator__pb2.ConfigurationRequest.SerializeToString,
            Configurator__pb2.ConfigurationContainer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
