# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import OrderBoard_pb2 as OrderBoard__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SubscribtionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeForMessages = channel.unary_stream(
                '/orders.Subscribtion/SubscribeForMessages',
                request_serializer=OrderBoard__pb2.SubscribtionRequest.SerializeToString,
                response_deserializer=OrderBoard__pb2.Message.FromString,
                )


class SubscribtionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeForMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscribtionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeForMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeForMessages,
                    request_deserializer=OrderBoard__pb2.SubscribtionRequest.FromString,
                    response_serializer=OrderBoard__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.Subscribtion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Subscribtion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeForMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orders.Subscribtion/SubscribeForMessages',
            OrderBoard__pb2.SubscribtionRequest.SerializeToString,
            OrderBoard__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class OrderBoardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrder = channel.unary_unary(
                '/orders.OrderBoard/GetOrder',
                request_serializer=OrderBoard__pb2.OrderRequest.SerializeToString,
                response_deserializer=OrderBoard__pb2.Order.FromString,
                )
        self.GetOrder2 = channel.unary_unary(
                '/orders.OrderBoard/GetOrder2',
                request_serializer=OrderBoard__pb2.OrderRequest.SerializeToString,
                response_deserializer=OrderBoard__pb2.Order.FromString,
                )
        self.PostOrder = channel.unary_unary(
                '/orders.OrderBoard/PostOrder',
                request_serializer=OrderBoard__pb2.Order.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetChatInfo = channel.unary_unary(
                '/orders.OrderBoard/GetChatInfo',
                request_serializer=OrderBoard__pb2.ChatInfoRequest.SerializeToString,
                response_deserializer=OrderBoard__pb2.ChatInfo.FromString,
                )
        self.PostReport = channel.unary_unary(
                '/orders.OrderBoard/PostReport',
                request_serializer=OrderBoard__pb2.Report.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.PostEntity = channel.unary_unary(
                '/orders.OrderBoard/PostEntity',
                request_serializer=OrderBoard__pb2.Entity.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.StreamMessages = channel.stream_unary(
                '/orders.OrderBoard/StreamMessages',
                request_serializer=OrderBoard__pb2.Message.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DownloadMessages = channel.unary_stream(
                '/orders.OrderBoard/DownloadMessages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=OrderBoard__pb2.SavedMessage.FromString,
                )


class OrderBoardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBoardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=OrderBoard__pb2.OrderRequest.FromString,
                    response_serializer=OrderBoard__pb2.Order.SerializeToString,
            ),
            'GetOrder2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder2,
                    request_deserializer=OrderBoard__pb2.OrderRequest.FromString,
                    response_serializer=OrderBoard__pb2.Order.SerializeToString,
            ),
            'PostOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PostOrder,
                    request_deserializer=OrderBoard__pb2.Order.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetChatInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatInfo,
                    request_deserializer=OrderBoard__pb2.ChatInfoRequest.FromString,
                    response_serializer=OrderBoard__pb2.ChatInfo.SerializeToString,
            ),
            'PostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.PostReport,
                    request_deserializer=OrderBoard__pb2.Report.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PostEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.PostEntity,
                    request_deserializer=OrderBoard__pb2.Entity.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StreamMessages': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=OrderBoard__pb2.Message.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DownloadMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadMessages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=OrderBoard__pb2.SavedMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrderBoard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderBoard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/GetOrder',
            OrderBoard__pb2.OrderRequest.SerializeToString,
            OrderBoard__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrder2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/GetOrder2',
            OrderBoard__pb2.OrderRequest.SerializeToString,
            OrderBoard__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/PostOrder',
            OrderBoard__pb2.Order.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChatInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/GetChatInfo',
            OrderBoard__pb2.ChatInfoRequest.SerializeToString,
            OrderBoard__pb2.ChatInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/PostReport',
            OrderBoard__pb2.Report.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderBoard/PostEntity',
            OrderBoard__pb2.Entity.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/orders.OrderBoard/StreamMessages',
            OrderBoard__pb2.Message.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orders.OrderBoard/DownloadMessages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            OrderBoard__pb2.SavedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
