version: '3.4'


services:
  db:
    image: ${DOCKER_REGISTRY-}data_fair_db
    build:
      context: .
      dockerfile: Infrastructure/DataFairDB/Dockerfile
    restart: always
    ports:
      - "54321:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  notificationprovider:
    ports:
      - "5000:5000"
    restart: always
    image: ${DOCKER_REGISTRY-}notificationprovider
    build:
      context: .
      dockerfile: NotificationProvider/Dockerfile
    environment:
        GrpcUrl: ${GrpcUrl}
        ConnectionString: ${ConnectionString}
