name: Data Fair deploy

  
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Stop the daemon
        run: ssh ${{ secrets.MAIN_USERNAME }}@${{ secrets.MAIN_HOST }} -p 22 -no-antispoof -pw ${{ secrets.MAIN_PWD }} systemctl stop DataFair
          

        
