name: Data Fair deploy

on:
  push:
    branches: [ main ]

jobs:
  server-prepairing:
    runs-on: ubuntu-18.04
    steps:
    - name: Killing an deleting old service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key : ${{ secrets.MAIN_SSH_KEY }}
        passphrase: ${{ secrets.MAIN_PWD}}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          systemctl stop DataFair
          cd /bin
          rm -r -f /bin/DataFair
          
          
  build-and-deploy:
    needs: server-prepairing
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd DataFair
        dotnet build --output ../output --runtime ubuntu.18.04-x64
    - name: Copy .service file to output folder
      run: cp DataFair.service output/DataFair.service
    - name: Upload files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        source: "./output"
        target: "/bin/DataFair/"
    - name: server prepairing
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key : ${{ secrets.MAIN_SSH_KEY }}
        passphrase: ${{ secrets.MAIN_PWD}}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          mv /bin/DataFair/output/DataFair.service /etc/systemd/system/DataFair.service
          mv /bin/DataFair/output/* /bin/DataFair/
          rm /bin/DataFair/output/ -r
          chmod u+x /bin/DataFair/DataFair
          echo 'User ID=postgres;Password=${{ secrets.MAIN_PG_PWD }};Host=localhost;Port=5432;Database=test_db;Pooling=true'>>/bin/DataFair/settings.txt
          systemctl daemon-reload
          systemctl enable DataFair
          systemctl start DataFair
      
        
        
      



      
      
          
        
