name: Data Fair deploy

on:
  push:
    branches: [ main ]

jobs:
  server prepairing:
    runs-on: ubuntu-18.04
    steps:
    - name: Killing an deleting old service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          systemctl stop DataFair
          cd /root
          rm -r /root/DataFair
          
  build and deploy:
    needs: server prepairing
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd DataFair
        dotnet build --output ../output
    - name: Copy .service file to output folder
      run: cp DataFair.service output/DataFair.service
    - name: Upload files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        source: "./output"
        target: "/root/DataFair/"
    - name: server prepairing
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          mv /root/DataFair/output/DataFair.sevice /etc/systemd/system/DataFair.service
          mv /root/DataFair/output/* /root/DataFair/
          rm /root/DataFair/output/
          chmod u+x /root/DataFair/DataFair
          systemctl daemon-reload
          systemctl enable DataFair
          systemctl start DataFair
      
        
        
      



      
      
          
        
