name: Data Fair deploy


  
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        pwd
        dotnet build --output ./output
      
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - name: Killing an deleting old service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          systemctl stop DataFair
          cd /root
          rm -r /root/DataFair
          mkdir DataFair
    - name: Upload files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        password: ${{ secrets.MAIN_PWD }}
        port: ${{ secrets.MAIN_PORT }}
        source: "/home/runner/work/tg-data-miner/tg-data-miner/output/DataFair.dll"
        target: "/root/DataFair/"
      
      
          
        
