name: Data Fair docker deploy

on:
  push:
    branches: [ main ]
      
env:
  IMAGE_NAME: test-image
      
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          pwd
          ls
          docker build . --file Dockerfile
          
          
