name: Data Fair deploy

on:
  push:
    branches: [ main ]

jobs:
         
          
  build-and-deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd DataFair
        dotnet build --output ../output --runtime ubuntu.18.04-x64
    - name: Copy .service file to output folder
      run: cp DataFair.service output/DataFair.service
    - name: Upload files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key : ${{ secrets.MAIN_SSH_KEY }}
        passphrase: ${{ secrets.MAIN_PWD}}
        port: ${{ secrets.MAIN_PORT }}
        source: "./output"
        target: "/bin/DataFair2/"
        
      



      
      
          
        
