name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Stop the daemon
        env:
          USERNAME: ${{ secrets.MAIN_USERNAME }}
          HOST: ${{ secrets.MAIN_HOST }}
          PASSWORD: ${{ secrets.MAIN_PWD }}
        run: systemctl stop DataFair

        
