name: Data Fair Noti Bot docker deploy

on:
  push:
    branches: [ main ]
      
env:
  IMAGE_NAME: test-image
      
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./ObserverBot.Service/Dockerfile
          push: true
          tags: vladzvx/tg-data-miner:noti-bot
          
          
      #- name: deploy
       # uses: appleboy/ssh-action@master
      #  with:
       #   host: ${{ secrets.BOT_HOST }}
      #    username: ${{ secrets.BOT_USER }}
       #   password : ${{ secrets.BOT_PWD }}
      #    port: 22
     #     script: |
         #   docker stop search_bot
          #  docker stop search_bot2
           # docker rm search_bot
       #     docker rm search_bot2
       #     docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
       #     docker pull vladzvx/tg-data-miner:data-fair-bot
       #     docker run --name search_bot -d -p 5003:5003 --env GrpcUrl=${{ secrets.MAIN_HOST }}:5005 --env Token=${{ secrets.PROD_SEARCH_BOT_TOKEN2 }} vladzvx/tg-data-miner:data-fair-bot

