name: Observer compose deploy

on:
  push:
    branches: [ main ]

jobs:
  uploading:
    runs-on: ubuntu-18.04
    steps:
    - name: Cloning repo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key : ${{ secrets.MAIN_SSH_KEY }}
        passphrase: ${{ secrets.MAIN_PWD}}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          cd /bin
          sudo > /.env

          
          
          
          
          
