name: Observer compose deploy

on:
  push:
    branches: [ main ]

jobs:
  uploading:
    runs-on: ubuntu-18.04
    steps:
    - name: Cloning repo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key : ${{ secrets.MAIN_SSH_KEY }}
        passphrase: ${{ secrets.MAIN_PWD}}
        port: ${{ secrets.MAIN_PORT }}
        script: |
          cd /bin
          sudo echo "${{ secrets.NOTI_ENV }}" > /.env
          sudo rm -r tg-data-miner
          sudo git clone https://${{ secrets.GIT_PWD }}@github.com/vladzvx/tg-data-miner.git
          sudo chmod u+x tg-data-miner
          sudo mv .env tg-data-miner
          cd tg-data-miner
          
          
          
          
          
